### ISSUE TITLE
Should there be an API for restricting which roles a `CRUDView` has?

### ISSUE THREAD

**Issue by joshuadavidthomas** [westerveltco/neapolitan#4]
https://github.com/carltongibson/neapolitan/issues/32

**Comment by carltongibson** [comment]
@joshuadavidthomas Yes, yes there should. Relatedly there should also be API for routing extra (custom) roles. 

I've got sketched notes about this, but the essence of it is that I'd like to keep in contained around `get_urls()`. 

_Maybe_ for this folks would pass a list if CRUD roles... `crud_roles={Role.LIST, Role.DETAIL}`. 

I imagine folks would override in the subclass to specify this, rather than call it in the URL conf.

**Comment by carltongibson** [comment]
This is in https://github.com/carltongibson/neapolitan/pull/44
